import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navebar from "../components/Navebar";
import HeroSection from "../components/HeroSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "first app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-neutral-800	">
      <body className={inter.className}>
        <Navebar />
        <HeroSection />
        {children}
      </body>
    </html>
  );
}
